name: racemate_clone_task
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# ---------- PACKAGES ---------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility
  flutter_screenutil: ^5.9.0
  http: ^1.2.1
  intl: ^0.19.0
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0

  # Icons
  cupertino_icons: ^1.0.6

  # State Managment
  get: ^4.6.6
  get_storage: ^2.1.1

  # product-specific
  stylish_bottom_bar: ^1.1.0

# ---------- DEV ONLY PACKAGES ---------- #
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# ---------- ASSETS ---------- #
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/races_images/